/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.gui.component;

import java.awt.Color;
import java.awt.Font;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.border.CompoundBorder;
import java.awt.*;

/**
 *
 * @author Encin
 */
public class CartLowStockAlert extends javax.swing.JPanel {
    
    private JLabel lblProductName;
    private JLabel lblStockStatus;
    private JButton btnRestock;
    /**
     * Creates new form CartLowStockAlert
     */
    public CartLowStockAlert() {
        initComponents();
        setProperties();
    }
    
    private void setProperties() {
        // Set panel properties
        setBackground(new Color(249, 250, 251)); // #F9FAFB
        setBorder(new CompoundBorder(
            new EmptyBorder(5, 5, 5, 5),
            new RoundedBorder(8, new Color(240, 240, 240))
        ));
        setPreferredSize(new Dimension(280, 70));
        setLayout(new BorderLayout(10, 5));
        
        // Create main content panel
        JPanel contentPanel = new JPanel();
        contentPanel.setLayout(new BoxLayout(contentPanel, BoxLayout.Y_AXIS));
        contentPanel.setBackground(new Color(249, 250, 251));
        
        // Product info panel
        JPanel topPanel = new JPanel();
        topPanel.setLayout(new BoxLayout(topPanel, BoxLayout.X_AXIS));
        topPanel.setBackground(new Color(249, 250, 251));
        
        lblProductName = new JLabel("Producto 1");
        lblProductName.setFont(new Font("Segoe UI", Font.BOLD, 14));
        
        // Stock status panel
        JPanel bottomPanel = new JPanel();
        bottomPanel.setLayout(new BoxLayout(bottomPanel, BoxLayout.X_AXIS));
        bottomPanel.setBackground(new Color(249, 250, 251));
        
        lblStockStatus = new JLabel("Quedan solo 2 items");
        lblStockStatus.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lblStockStatus.setForeground(new Color(239, 68, 68)); // Color rojo para alertas
        
        // Botón de Resurtir
        btnRestock = new JButton("Resurtir");
        btnRestock.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        btnRestock.setForeground(new Color(59, 130, 246)); // Color azul para el botón
        btnRestock.setBorderPainted(false);
        btnRestock.setContentAreaFilled(false);
        btnRestock.setFocusPainted(false);
        btnRestock.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        topPanel.add(lblProductName);
        topPanel.add(Box.createHorizontalGlue());
        topPanel.add(btnRestock);
        
        bottomPanel.add(lblStockStatus);
        bottomPanel.add(Box.createHorizontalGlue());
        
        contentPanel.add(topPanel);
        contentPanel.add(Box.createVerticalStrut(5));
        contentPanel.add(bottomPanel);
        
        add(contentPanel, BorderLayout.CENTER);
    }
    
    // Método público para actualizar la información de la alerta
    public void setAlertInfo(String productName, int remainingItems) {
        lblProductName.setText(productName);
        lblStockStatus.setText("Quedan solo " + remainingItems + " items");
    }
    
    // Método para agregar un listener al botón de resurtir
    public void addRestockListener(java.awt.event.ActionListener listener) {
        btnRestock.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
