/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.gui.home;

/**
 *
 * @author Encin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jpDashboard = new javax.swing.JPanel();
        jlIconD = new javax.swing.JLabel();
        jlbuttonDasboard = new javax.swing.JLabel();
        jpInventory = new javax.swing.JPanel();
        jpSale = new javax.swing.JPanel();
        jpReports = new javax.swing.JPanel();
        jpInvoices = new javax.swing.JPanel();
        jpAlerts = new javax.swing.JPanel();
        jpSettings = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jpView = new javax.swing.JPanel();
        jlTitleD = new javax.swing.JLabel();
        jpTotalSales = new javax.swing.JPanel();
        jpTotalProducts = new javax.swing.JPanel();
        jpLowStock = new javax.swing.JPanel();
        jpRecentSales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jpLowStockAlert = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBackground(new java.awt.Color(255, 255, 255));
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitle.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jlTitle.setText("TechPoint Manager");
        jpMenu.add(jlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 138, 24));
        jlTitle.getAccessibleContext().setAccessibleName("jlTitle");

        jpMenu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 20));

        jpDashboard.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        jpDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlIconD.setBackground(new java.awt.Color(255, 255, 255));
        jlIconD.setForeground(new java.awt.Color(51, 153, 255));
        jlIconD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/images/dash_select.png"))); // NOI18N

        jlbuttonDasboard.setText("Dashboard");

        javax.swing.GroupLayout jpDashboardLayout = new javax.swing.GroupLayout(jpDashboard);
        jpDashboard.setLayout(jpDashboardLayout);
        jpDashboardLayout.setHorizontalGroup(
            jpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDashboardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jlIconD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbuttonDasboard, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpDashboardLayout.setVerticalGroup(
            jpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDashboardLayout.createSequentialGroup()
                .addGroup(jpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlbuttonDasboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlIconD, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpMenu.add(jpDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 40));

        javax.swing.GroupLayout jpInventoryLayout = new javax.swing.GroupLayout(jpInventory);
        jpInventory.setLayout(jpInventoryLayout);
        jpInventoryLayout.setHorizontalGroup(
            jpInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jpInventoryLayout.setVerticalGroup(
            jpInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jpMenu.add(jpInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, 40));

        javax.swing.GroupLayout jpSaleLayout = new javax.swing.GroupLayout(jpSale);
        jpSale.setLayout(jpSaleLayout);
        jpSaleLayout.setHorizontalGroup(
            jpSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jpSaleLayout.setVerticalGroup(
            jpSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jpMenu.add(jpSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, 40));

        javax.swing.GroupLayout jpReportsLayout = new javax.swing.GroupLayout(jpReports);
        jpReports.setLayout(jpReportsLayout);
        jpReportsLayout.setHorizontalGroup(
            jpReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jpReportsLayout.setVerticalGroup(
            jpReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jpMenu.add(jpReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 150, 40));

        javax.swing.GroupLayout jpInvoicesLayout = new javax.swing.GroupLayout(jpInvoices);
        jpInvoices.setLayout(jpInvoicesLayout);
        jpInvoicesLayout.setHorizontalGroup(
            jpInvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jpInvoicesLayout.setVerticalGroup(
            jpInvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jpMenu.add(jpInvoices, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 40));

        javax.swing.GroupLayout jpAlertsLayout = new javax.swing.GroupLayout(jpAlerts);
        jpAlerts.setLayout(jpAlertsLayout);
        jpAlertsLayout.setHorizontalGroup(
            jpAlertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jpAlertsLayout.setVerticalGroup(
            jpAlertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jpMenu.add(jpAlerts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 150, 40));

        javax.swing.GroupLayout jpSettingsLayout = new javax.swing.GroupLayout(jpSettings);
        jpSettings.setLayout(jpSettingsLayout);
        jpSettingsLayout.setHorizontalGroup(
            jpSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jpSettingsLayout.setVerticalGroup(
            jpSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jpMenu.add(jpSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 150, 40));

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 540));

        jSeparator1.setBackground(new java.awt.Color(229, 231, 235));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235)));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 2, 540));

        jpView.setBackground(new java.awt.Color(249, 250, 251));
        jpView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitleD.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jlTitleD.setText("Dashboard");
        jpView.add(jlTitleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 680, -1));

        jpTotalSales.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpTotalSalesLayout = new javax.swing.GroupLayout(jpTotalSales);
        jpTotalSales.setLayout(jpTotalSalesLayout);
        jpTotalSalesLayout.setHorizontalGroup(
            jpTotalSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jpTotalSalesLayout.setVerticalGroup(
            jpTotalSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jpView.add(jpTotalSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 50, 200, 130));

        jpTotalProducts.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpTotalProductsLayout = new javax.swing.GroupLayout(jpTotalProducts);
        jpTotalProducts.setLayout(jpTotalProductsLayout);
        jpTotalProductsLayout.setHorizontalGroup(
            jpTotalProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jpTotalProductsLayout.setVerticalGroup(
            jpTotalProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jpView.add(jpTotalProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jpLowStock.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpLowStockLayout = new javax.swing.GroupLayout(jpLowStock);
        jpLowStock.setLayout(jpLowStockLayout);
        jpLowStockLayout.setHorizontalGroup(
            jpLowStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jpLowStockLayout.setVerticalGroup(
            jpLowStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jpView.add(jpLowStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 200, -1));

        jpRecentSales.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Ventas recientes");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpRecentSalesLayout = new javax.swing.GroupLayout(jpRecentSales);
        jpRecentSales.setLayout(jpRecentSalesLayout);
        jpRecentSalesLayout.setHorizontalGroup(
            jpRecentSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRecentSalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRecentSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpRecentSalesLayout.setVerticalGroup(
            jpRecentSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRecentSalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpView.add(jpRecentSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 220, 320, 280));

        jpLowStockAlert.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Alertas de Bajo Stock");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpLowStockAlertLayout = new javax.swing.GroupLayout(jpLowStockAlert);
        jpLowStockAlert.setLayout(jpLowStockAlertLayout);
        jpLowStockAlertLayout.setHorizontalGroup(
            jpLowStockAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLowStockAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLowStockAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpLowStockAlertLayout.setVerticalGroup(
            jpLowStockAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLowStockAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpView.add(jpLowStockAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 320, 280));

        getContentPane().add(jpView, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 0, 740, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlIconD;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JLabel jlTitleD;
    private javax.swing.JLabel jlbuttonDasboard;
    private javax.swing.JPanel jpAlerts;
    private javax.swing.JPanel jpDashboard;
    private javax.swing.JPanel jpInventory;
    private javax.swing.JPanel jpInvoices;
    private javax.swing.JPanel jpLowStock;
    private javax.swing.JPanel jpLowStockAlert;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpRecentSales;
    private javax.swing.JPanel jpReports;
    private javax.swing.JPanel jpSale;
    private javax.swing.JPanel jpSettings;
    private javax.swing.JPanel jpTotalProducts;
    private javax.swing.JPanel jpTotalSales;
    private javax.swing.JPanel jpView;
    // End of variables declaration//GEN-END:variables
}
